### ISSUE TITLE
Issues on Home Assistant 0.106.X

### ISSUE THREAD

**Issue by madtoko** [custom-cards/dual-gauge-card#27] opened 2020-03-10 12:52 UTC
Hi

After Home Assistant update to 0.106.x the dual gauges cards not is showing correctly.

**Comment by dede34fr** [comment] 2020-03-14 13:05
Same. Error "Cannot assign to read only property 'min' of object '#<Object>'".
Also, documentation is not up to date : HCS requires a different path name for the url. And the docs shows type "module" in one page, and type "js" in another page (readme).

**Comment by papperone** [comment] 2020-03-15 09:32
same here, and the author does not seems to be active nor replying afte so many days 0.106 has broken this (and many other!) cards....
anyone know a suitable replacement that works?

**Comment by superforno** [comment] 2020-03-16 17:49
Confirm, after 0.106 update, getting this: "Cannot add property min, object is not extensible"

**Comment by madtoko** [comment] 2020-03-17 01:31
Yes, Cannot add property min, object is not extensible"

Em seg, 16 de mar de 2020 14:49, Enrico <notifications@github.com> escreveu:

**Comment by dede34fr** [comment] 2020-03-23 15:31
Is there someone working on it? Or is there an alternative solution to do the same thing?

**Comment by superforno** [comment] 2020-03-24 11:58
If it is not mantained, I can try to fork it, add the fix and make a pull request.
Have it fixed on my installation some days ago

**Comment by dede34fr** [comment] 2020-03-28 16:22
would be great if you could fix that dual gauge

**Comment by superforno** [comment] 2020-04-01 21:46
> would be great if you could fix that dual gauge

Created a pull request to integrate the fix. Let's see if it will be integrated.

**Comment by Rocka84** [comment] 2020-04-20 12:18
Hi!
This is a duplicate of #24 which was fixed by now.
Please open a new issue if you still have problems.

**Closed by Rocka84** 2020-04-20 12:18 UTC
