### ISSUE TITLE
Dual-gauge-card on Blacklist

### ISSUE THREAD

**Issue by bschatzow** [custom-cards/dual-gauge-card#31] opened 2020-04-13 14:46 UTC
In HACS I get error that the dual-gauge-card is on the blacklist.

**Comment by fudu** [comment] 2020-04-14 09:25
Same issue.
And cannot uninstall it, too

`Dettagli registro (ERROR)
Logger: hacs
Source: custom_components/hacs/ws_api_handlers.py:252
First occurred: 11:22:00 (2 occurrences)
Last logged: 11:23:19

Repository is in the blacklist.`
`Dettagli registro (WARNING)
Logger: hacs
Source: custom_components/hacs/hacsbase/__init__.py:337
First occurred: 11:21:24 (1 occurrences)
Last logged: 11:21:24

You have custom-cards/dual-gauge-card installed with HACS this repository has been removed, please consider removing it. Removal reason (stale)`

`Dettagli registro (ERROR)
Logger: hacs
Source: custom_components/hacs/http.py:76
First occurred: 11:22:12 (1 occurrences)
Last logged: 11:22:12

Tried to serve up '/config/www/community/dual-gauge-card/null' but it does not exist`

**Comment by jojoro1** [comment] 2020-04-18 19:36
I have the same issue

**Comment by carldebilly** [comment] 2020-04-18 22:42
Anybody knows why?

**Comment by Rocka84** [comment] 2020-04-20 18:35
Hi everybody!
I know why this was blacklisted and its totally my fault :-(
This card got blacklisted because until recently there was no development and the card didn't work with home assistant 0.106 and above.
I opened a pull request to hacs to unblacklist it and hope for the best.

@fudu 
Why you couldn't uninstall it is beyond my knowledge. Let's hope it gets unblacklisted and uninstallation is fixed by that too. If not please open an new issue.

**Comment by jameshiscott** [comment] 2020-04-20 22:16
The uninstall was fixed in the latest HACS. But now i want it back :)

**Comment by bschatzow** [comment] 2020-04-21 20:26
Still shows in blacklist.

**Comment by Rocka84** [comment] 2020-04-21 21:33
Yes, it does :slightly_frowning_face: 
I was hoping that this maybe would resolve itself with time but it seems I have to investigate this soon, hopefully tomorrow. I will post an update here and in the home assistant community as soon as I know whats going on.

**Comment by bschatzow** [comment] 2020-04-22 00:09
I would have thought if ludeeus closed the issue it would be fixed as he blacklisted it.

**Comment by bschatzow** [comment] 2020-04-22 21:48
Just check after HACS update and no longer on blacklist.

**Comment by Rocka84** [comment] 2020-04-23 11:29
Confirmed! We're back to HACS!

Please upgrade HACS to at least 0.24.2 if you still can't find this card.

**Closed by Rocka84** 2020-04-23 11:29 UTC
