### ISSUE TITLE
White screen on non existant sensors

### ISSUE THREAD

**Issue by maulwuff** [custom-cards/dual-gauge-card#35] opened 2020-05-22 22:33 UTC
I have sensors, which disappear when I have to restart HA. 
This makes the dual gauge card render an entire tab/view as WSOD. I have to remove the card via raw config editor to see the other cards again.

The default behaviour is, to show something like "Entity not available: sensor.vehicle_bat_soc" and keep the rest of the page working. Would this be doable for dual gauge card, too?

HA: 0.110.1
DGC: 0.5.2

**Comment by KTibow** [comment] 2020-07-22 17:32
Duplicate of #23

**Comment by maulwuff** [comment] 2020-07-22 20:31
#23 talks about not being able to open the config editor of the card. 
This one makes the whole Lovelace view (i.e. reachable via /lovelace/default_view) go blank. There is no editor I could use for the card.

**Comment by KTibow** [comment] 2020-07-22 20:37
Umm... So you can't see the three dots?

**Comment by maulwuff** [comment] 2020-07-22 20:53
right, it's the whole "view" not just the gauge card inside the view.
To make it really clear: A view in lovelace is: go to "configure UI" via the 3 dots on the upper right of the browser page, click "add view" > that type of thingy is what goes blank. 
That's also the only way to get to the yaml editor to remove the gauge card.

**Comment by KTibow** [comment] 2020-07-22 21:03
Oh...

> There is no editor I could use for the card.

!= `There is no editor I could use for Lovelace.`

**Comment by maulwuff** [comment] 2020-07-22 21:38
You still think, it's the same issue? #23 doesn't talk about non existant sensors making the whole page unusable. I understood, only editing is an issue there.

**Comment by KTibow** [comment] 2020-07-22 21:48
Anyway I'm sending in a PR.

**Closed** 2021-05-09 11:25 UTC
