### ISSUE TITLE
Cannot add property min, object is not extensible

### ISSUE THREAD

**Issue by vlumikero** [custom-cards/dual-gauge-card#25] opened 2020-03-07 18:29 UTC
Hi,

My dual gauge card was working fine until a few weeks ago, now I'm getting this error: "Cannot add property min, object is not extensible".

The config is 
inner:
  entity: sensor.hw_top
  label: HW Top
  unit: °C
max: 60
outer:
  entity: sensor.hw_load
  label: HW Load
  unit: °C
title: Varmvatten
type: 'custom:dual-gauge-card'

Any ideas?

Thanks,
Ville

**Comment by PonyOny** [comment] 2020-03-08 23:07
Same, here I have to manually add all the Config structure manually at it seems it's starting as "read only" no properties can be appended or changed and even adding all manually it still does not work as it changes values on the arrays and it throws errors
![image](https://user-images.githubusercontent.com/17080292/76172839-e9493100-6199-11ea-85f5-7ae9a27d6510.png)

![image](https://user-images.githubusercontent.com/17080292/76172804-b010c100-6199-11ea-92a9-628d161036ee.png)

**Comment by PonyOny** [comment] 2020-03-08 23:23
Changing the JS file like this makes it work again
![image](https://user-images.githubusercontent.com/17080292/76173044-fa933d00-619b-11ea-9d7a-1f634584c27a.png)
just add the top line and remove the assignation where the second arrow points
`this.config = config;`

**Comment by TheMrg** [comment] 2020-04-01 15:56
Same issue. How to fix?

**Comment by Rocka84** [comment] 2020-04-20 12:15
Hi!
This is a duplicate of #24 which was fixed by now.
Please open a new issue if you still have problems.

**Closed by Rocka84** 2020-04-20 12:15 UTC
